### PR TITLE
useLayoutEffect instead of useEffect

### PR DESCRIPTION
**Pull request by smblee**
There is a flash of unwanted content for a brief second if using `useEffect`

`useLayoutEffect` seems to resolve this issue

### CODE REVIEW

**Comment by iiroj** [comment]
Hello and thanks for the PR,

did you look at the README under [Return values](https://github.com/iiroj/use-breakpoint#return-values)? Are you experiencing the case **2**?

The `useLayoutEffect` introduces an annoying warning during development in server-side environments, so I'd rather avoid using it if possible.

**Comment by smblee** [comment]
the default will incur same behavior if you start from mobile and vice versa. I think you can use a similar pattern as `use-media` library and expose both versions: one using layoutEffect and another using regular effect.

https://github.com/streamich/use-media/blob/master/src/useMedia.ts#L50

**Comment by iiroj** [comment]
Thanks, I will investigate a bit before merging.

**Comment by iiroj** [comment]
If you clone this repo and start the Storybook server, do you experience the flash there? Can you better describe it so that I can try to reproduce it?

**Comment by smblee** [comment]
Was able to confirm on storybook. It's a bit more apparent on a CRA

**Comment by iiroj** [comment]
I can only reproduce the flash in the second story (using a default value with `hydrateInitial: true`:

Screenshot 2021-05-24 at 17 18 52

Pleas try setting the third argument `hydrateInitial: false` if it helps.

**Comment by smblee** [comment]
Please try setting it up in a client sided React app (CRA) and see if you can reproduce the issue.

**Comment by zip184** [comment]
I've been able to reproduce the issue via CRA, but not super consistently. It's very quick. When I manually update useEffect to useLayoutEffect in node_modules, I'm not able to reproduce it anymore. This makes sense according to this blog. https://kentcdodds.com/blog/useeffect-vs-uselayouteffect "useLayoutEffect: If you need to mutate the DOM and/or do need to perform measurements"

**Comment by iiroj** [comment]
Well, let's merge this as a `fix` and see what happens, thanks @smblee,  and also @zip184

**Comment by iiroj** [comment]
Welp, you need to fix ESLint errors first, @smblee:

https://github.com/iiroj/use-breakpoint/pull/9/checks?check_run_id=2657718971#step:5:14

If you don't mind, please also prefix the commit message with `fix: `

**Comment by iiroj** [comment]
Thanks! This included in [v2.0.1](https://github.com/iiroj/use-breakpoint/blob/master/CHANGELOG.md#201-2021-05-27).

**Pull request merged**
